### ISSUE TITLE
more statistics in .report when matched column have difference in value

### ISSUE THREAD

**Issue by tczhao** [capitalone/datacompy#101]
I think producing statics like
absolute difference and the relative difference between
- mean
- median
- percentiles
when column schema matches but have the difference in values

can be very helpful to day-to-day data science summary comparison.

Any thoughts?, happy to make a PR if there's no resource

**Comment by fdosani** [comment]
@tczhao thanks for the suggestion. I think I'm aligned with this. @jborchma @elzzhu thoughts on this? For numeric fields this would make a lot of sense.

**Comment by fdosani** [comment]
@tczhao Closing this issue since I haven't heard back. Feel free to reopen if needed.
