### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by trollcodelord** [capitalone/datacompy#106]
raise ValueError("{} must have all columns from join_columns".format(index))

ValueError : df1 must have all columns from join_colums

Code 
    compare = datacompy.Compare(df1,df2, join_columns =list(df1.columns), df1_name = 'XVY', df2_name = 'SAS')
    
    compare.matches(ignore_extra_columns=False)

**Comment by fdosani** [comment]
Thanks for opening an issue. Could you output the column names from `df1` and `df2`? I'm going to guess that your `join_columns` don't match between them based on the error message.

**Comment by fdosani** [comment]
Going to close this issue since I haven't heard back. Feel free to reopen it if needed.
