### ISSUE TITLE
Display all columns instead of first 10 columns

### ISSUE THREAD

**Issue by bendanye** [capitalone/datacompy#115]
Hi there,

Is there a way to show all the columns for row which unable to find either on dataframes that used for comparing to overwrite current behaviours that only show first 10 columns? The reason is i may have more than 10 columns 

For example in the current behaviour:

```
Number of rows in common: 4
Number of rows in Expected but not in Actual: 1
Number of rows in Actual but not in Expected: 1

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 17
Total number of values which compare unequal: 0

Sample Rows Only in Expected (First 10 Columns)
```

**Comment by fdosani** [comment]
I think we can add this in as an option.  I can try and work on this tomorrow or early next week. In the meantime you can always clone the repo and change those 2 lines of code and run it in editable mode. Sent from ProtonMail for iOS On Thu, Oct 14, 2021 at 9:33 PM, Ng Shen Soon Benjamin ***@***.***> wrote:  
@fdosani Yes correct, that what i meant
