### ISSUE TITLE
Export datacompy  report as HTML

### ISSUE THREAD

**Issue by avico78** [capitalone/datacompy#133]
Is there an option to export datacompy to HTML?

**Comment by weigao-123** [comment]
Hi, @fdosani ,

Maybe you can consider a simple wrap function around Compare.report() as follows:
`html_report = compare.report().replace('\n', '<br>').replace(' ', '&nbsp;')
html_report = f'<pre>{html_report}</pre>'
with open('test.html', 'w') as f:
    f.write(html_report)`

**Comment by fdosani** [comment]
I’ll see if I can come up with something in a bit here. Happy to accept a PR too.

**Comment by fdosani** [comment]
> I would also love the html output of comparison. One suggestion is we could get some ideas from this project:
> https://github.com/fbdesignpro/sweetviz

I actually have a fix in. Just need a review and we can add HTML support.
