### ISSUE TITLE
Reporting more number of rows unique in source and not in target. Currently its limited to 10

### ISSUE THREAD

**Issue by sujitsatapathy84** [capitalone/datacompy#134]
How to get more rows shown in the report like for rows available in source but not in target, if I want to see may be 100 rows. How do I do that?

I tried using print(compare.df1_unq_rows(sample_count=50),file=tgtuniqrows) but it gave me error as 
print(compare.df1_unq_rows(sample_count=50),file=tgtuniqrows)
TypeError: 'DataFrame' object is not callable

Can you please help here?

**Comment by fdosani** [comment]
Hi there,

It seems like you are trying to pass `sample_count=50` to a dataframe which won't work. `compare.df1_unq_rows` is just a Pandas [DataFrame](https://github.com/capitalone/datacompy/blob/develop/datacompy/core.py#L74).

So you could use `head(100)` on `compare.df1_unq_rows`. Something like:

```python
print(compare.df1_unq_rows.head(100), file=tgtuniqrows)
```

Does the above work?

**Comment by sujitsatapathy84** [comment]
Hi,
Thanks for your response. I tried this but No it doesn't give the desired output, it still dumps first 5 and last 5 rows . The only difference when .head(100) given is, it gives first 5 and last 5 rows out of the top 100 rows whereas if it is not given then it still give first 5 and last 5 rows out of the total unique rows.

My requirement, is I want to get all uniq rows in df1 not in df2. If its not possible to get all then at least I want the limit of rows to be 1000. Can you please guide me on this.

Thanks
Sujit
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/101582536/158755482-2e999c37-44ce-4c80-a317-43e4a9cb06a6.png">

**Comment by sujitsatapathy84** [comment]
compare=datacompy.Compare(df2,df1,join_columns=('contractId','contractSubscriptionId'))
print(compare.df1_unq_rows.head(100),file=tgtuniqrows)
print(compare.df2_unq_rows.head(100),file=srcuniqrows)

**Comment by fdosani** [comment]
If it isn't showing all the rows you can set pandas to display everything like so: 

```python
pandas.set_option('display.max_rows', None)
```

`df1_unq_rows` should give you the distinct rows in df1:

```
    df1_unq_rows : pandas ``DataFrame``
        All records that are only in df1 (based on a join on join_columns)
```

**Comment by fdosani** [comment]
I’m closing this issue as I haven’t heard back. Assuming this solved your question. Feel free to reopen if otherwise.
