### ISSUE TITLE
Cannot interpret 'datetime64[ns, UTC]' as a data type

### ISSUE THREAD

**Issue by Rstar1998** [capitalone/datacompy#160]
Any idea when support for `datetime64[ns, UTC]` will be implemented ?
I get this error `Cannot interpret 'datetime64[ns, UTC]' as a data type` when using compare function

**Comment by fdosani** [comment]
Happy to accept a PR for this from the community. I’ll add this to the backlog now 👍

**Comment by linbaiwh** [comment]
Hi @Rstar1998, can you provide an example?
numpy had this problem in the past, but it's fixed now. see https://github.com/numpy/numpy/pull/19269

Thanks!
