### ISSUE TITLE
join_columns is changing the content's column 

### ISSUE THREAD

**Issue by FrancisMorelli** [capitalone/datacompy#163]
Hi there.
In my join_columns selection is a column is numbers as strings that someones begins if 0, and when I run the report, the report swipe the zeros in the beginning of those item. Is there an way to not change those items, bringing the same string in the dataframe's column?

**Comment by fdosani** [comment]
Hi @FrancisMorelli can you post an example of what you are seeing and maybe what you'd like to happen. I think there might be something with Pandas (assuming you are using that) with column names starting with numbers. But the above info will help me debug a bit of what you are experiencing.

**Comment by FrancisMorelli** [comment]
I managed to convert into str. It worked. Thanks, @fdosani
