### ISSUE TITLE
Error in compare.report : Sample Values with Unequal Values

### ISSUE THREAD

**Issue by Madaditya** [capitalone/datacompy#17]
The output for report under section : Sample Values with Unequal Values

Shows same values for df1 and df2

> no    site_id  net_revenue (df1)  net_revenue (df2)
> 46   TRVED01             63.234000             63.234000
> 49  TRVEGH01            236.445673            236.445673

**in actual it is**

>no    site_id  net_revenue (Source)  net_revenue (Target)
> 46   TRVED01             63.234             63.234000
> 49  TRVEGH01            236.4456732            236.445673

**Comment by theianrobertson** [comment]
Hmm, yeah that could be a floating point representation issue.  Do you have a small code snippet that would reproduce this issue that you would be able to post?  Thanks for raising!

**Comment by fdosani** [comment]
@Madaditya Not sure if you have a snippet? If I don't hear back in a few days I'll consider this issue closed. Thanks!

**Comment by fdosani** [comment]
Closing the issue. Please feel free to reopen if you have time to provide details.
