### ISSUE TITLE
bump up minimum python version to 3.8

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#173]
There are some security vulns which keep coming up with Python 3.7 support. In the next release (0.9.x) we should drop Python 3.7 support. Should be an easy change and fix. 

- Following: https://github.com/capitalone/datacompy/blob/develop/setup.cfg#L14 should become `>=3.8.0`
- Doc / README updates would be needed also

**Comment by alegarpa** [comment]
Hi @fdosani ! I wanted to help contribute to this library and I wanted ask if this was still available for pick-up? 

I was also interested at looking into:
https://github.com/capitalone/datacompy/issues/6

I got laid off a while back so I want to spend some of my free time contributing to this library and learning about it.  I'd like to give back to the open source community now that I have a lot more software engineering experience.

**Comment by fdosani** [comment]
Hey @alegarpa Absolutely! Would love additional help if you have time.
Sorry to hear about the layoff. I'm hoping things are working out better for you.

This one should be relatively easy, since it would be mostly housekeeping stuff around the package and metadata.
I know we also could change to using f-strings everywhere too.

**Comment by fdosani** [comment]
@alegarpa Just wanted to touch base and see if you were still working on this? If not I can pick it up since I'd like to make suer we are bumping up to 3.8 for the next release.
