### ISSUE TITLE
compare report could output decimal actual precision

### ISSUE THREAD

**Issue by swloveydp** [capitalone/datacompy#190]
hi i use the datacompy compare two excel data, also i could see the diff between the two file, due to the limit of decimal precison , i cloude see the actual data in the output such as 
    data1(Original)  data1(New)
19         10.695709    10.695709
20         10.695709    10.695709
so i want konw dose there have method to output decimal actual precision??
thanks

**Comment by fdosani** [comment]
Hi @swloveydp Sorry for the confusion but I'm not really following the question here.
You want to change the precision of the comparison?

In the [Compare](https://capitalone.github.io/datacompy/api/datacompy.html#datacompy.core.Compare) instantiation there are are 2 fields: `abs_tol` and `rel_tol` . But I miight be misunderstanding the ask here.

**Comment by swloveydp** [comment]
thanks for you reply. i want change the compare report precision .  
follow is the part of  datacompy.Compare report:
Sample Rows with Unequal Values
-------------------------------

    data (Original)  data (New)
19           10.695709      10.695709
20           10.695709      10.695709
21           10.695709      10.695709
18           10.695709      10.695709
we can see it specify there have diff between the two files. due to the output precision. I can't see the difference of the original data directly in the report. I see the difference data in the report is equal, so i want know dose there have method to set the report decimal precision.
