### ISSUE TITLE
abs_tol does work when column have Special characters

### ISSUE THREAD

**Issue by swloveydp** [capitalone/datacompy#192]
![image](https://user-images.githubusercontent.com/16555783/226556246-66b8b927-f2dd-4b1f-b4ed-dbf1db0b7026.png)

hi i have problem when the  t value column have Special characters -， i want to compre two dataframe and set abs_tol=0.000001  ,due to there have special charater, datacompy del the t vlalue cloumn type as objetc , leads  abs_tol does not work. does there have method i can void this .thanks

**Comment by fdosani** [comment]
Closing, but feel free to reopen if this is still an issue.
