### ISSUE TITLE
consolidate the common functions between pandas and spark

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#197]
This is a quick follow up to #195.

 Since we are using an `abc` we can consolidate some of the functions between the 2 versions into the `BaseCompare`.

**Comment by janinebp** [comment]
I could help on this one

**Comment by fdosani** [comment]
Sure, this one might be meaty. I think I have some work done in #195 which has just been sitting, but I'm not sure if the Pandas Spark API is performant enough.
