### ISSUE TITLE
The intersection logic of Compare has problems.

### ISSUE THREAD

**Issue by goodwanghan** [capitalone/datacompy#221]
```pythpn
from datacompy import Compare
import pandas as pd

df1 = pd.DataFrame(dict(a=[0],b=[1]))
df2 = pd.DataFrame(dict(a=[0,0],b=[0,1]))

comp=Compare(df1, df2, join_columns=["a"])
print(comp.report())
```

We got this

```
Number of rows in common: 1
Number of rows in df1 but not in df2: 0
Number of rows in df2 but not in df1: 1

Number of rows with some compared columns unequal: 1
Number of rows with all compared columns equal: 0
```

It didn't capture the intersection of df1 and df2.

This is because the outer join https://github.com/capitalone/datacompy/blob/1de2f37f75064422be5f82cd8f35a0859f0fb8a0/datacompy/core.py#L272 is on `a` and a temp column, in `df1` the first row's temp value is 0, on `df2` the second row's temp value is 1. So with this implementation. we are not able to find the true intersection. And notice, sorting the two dataframes doesn't solve the problem, in this example, they are already fully sorted.

The solution may be joining on all columns, but that is expensive, so what other ways can we use to solve this issue?

**Comment by goodwanghan** [comment]
I think about it twice, this is even harder than I thought.

The big challenge is the floating columns. For example 0.99 and 1 can be considered same with certain atol and rtol. So the question is should we even compute the intersections? It's so expensive to make it right.

**Comment by fdosani** [comment]
@goodwanghan This might actually be covered in the docs: https://capitalone.github.io/datacompy/pandas_usage.html#duplicate-rows

This is sort of a known limitation and if you have a lot of dups you would really need to join on more fields to get more accurate results. I think the example in the docs sort of outlines what you have above and is the expected behaviour.

**Comment by fdosani** [comment]
Closing this. @goodwanghan feel free to reopen but I think this is known and documented.
