### ISSUE TITLE
Adding column naming differences to the column summary page

### ISSUE THREAD

**Issue by lva290** [capitalone/datacompy#222]
I have been using your package extensively and have found it to be incredibly useful for my needs in my work. However, I recently thought of a feature that could be useful for this package. I believe addressing this issue could enhance the functionality of the package. Furthermore, I would actually be really willing to contribute to this feature myself as i've been willing to contribute to open-source for awhile, but have never found the right use-case.

Here are the details of the issue I encountered:

Description:
In the scenario the column of the two Pandas data frames are different it does not show on the summary which columns are missing in one of the data frames. For example, in the example that is given in the `README` file, I think it would be useful to `date_fld` is missing in the second Pandas data frame.

Current Behavior:
It currently lists in the summary page that there are discrepancies in the data frames, but it doesn't show what's column is missing in the new dataframe. For small dataframes this is not much of an issue, but speaking from personal experience once you have more than 15-20 columns this feature would be really useful as it would quickly allow you to have this information. Currently, you have to look at this manually by looking at the Pandas dataframes. See a screenshot below for the current output on the sample provided in the `README` file.

<img width="420" alt="image" src="https://github.com/capitalone/datacompy/assets/14828174/7379267f-aa44-405b-ac46-2d426f999991">

Thank you for your attention to this matter. I appreciate your efforts in maintaining and improving this valuable open-source package. Is this a feature that sounds useful to more people? If so, please let me know and I can try to create a PR for this.

**Comment by fdosani** [comment]
@lva290 thanks for your message, appreciate you providing feedback and the kind words. I’m on vacation at the moment. Will be back on Wednesday. I’d love you have you contribute a PR if you have the time. I think displaying the columns would be a nice feature.  No rush, happy to continue the discussion on Wednesday. @NikhilJArora  and @ak-gupta of you have time would appreciate your thoughts too.

**Comment by lva290** [comment]
@fdosani thanks for the response! Great to hear it would be useful to you as well. I'll make sure to submit the pull request over the coming weeks when I find the time. Enjoy your holiday!

**Comment by fdosani** [comment]
Closing. Stale issue. Feel free to reopen this if someone want to pick this up.
