### ISSUE TITLE
Speed up spark unit tests

### ISSUE THREAD

**Issue by krishnanravi** [capitalone/datacompy#223]
The spark unit tests take anywhere between 3.5-4 mins today. We could speed this up significantly by resetting the spark shuffle partitions from its default 200 to 1.

Will help developers iterate faster by running the entire suite in few seconds instead of having of wait for 3-4 minutes. 

This is a simple change and I would like to create the PR if we agree.

**Comment by fdosani** [comment]
I just ran the unit tests on my home desktop and it ran in under a 45 seconds.

```
142 passed, 214 warnings in 41.90s
```
Going to close out this issue. Feel free to reopen it if you think otherwise. I don't think the action times should be used as the benchmark here. Since this is just automated CICD.
