### ISSUE TITLE
Feature Request: Ability to Update Compare Object Over Multiple Chunks

### ISSUE THREAD

**Issue by SuleymanKaya** [capitalone/datacompy#228]
Hello DataComPy team,

I am currently working with large datasets that require chunk processing due to memory constraints. I am using the Compare class to compare two dataframes, but I am facing a challenge when I need to process the data in chunks.

Currently, the Compare class performs the comparison when the object is created. This design doesn't allow for updating the comparison over multiple chunks of data. This means that I need to create a new Compare object for each chunk, resulting in multiple separate reports instead of a single comprehensive report.

I would like to propose a feature that allows the Compare object to be updated over multiple chunks. This could involve modifying the __init__ method and other methods of the Compare class, and potentially adding a new method that updates the current comparison results with a new chunk.

This feature would be extremely useful for those of us working with large datasets that can't be loaded into memory all at once. It would allow us to generate a single, comprehensive comparison report for the entire dataset, despite processing the data in chunks.

I understand that this would be a significant change to the current design of the Compare class, and I am open to discussion on how best to implement this feature. I also understand that this change could potentially affect other features and methods of the Compare class, and I am willing to work together to ensure that these are handled appropriately.

Thank you for considering this feature request. I believe it would be a valuable addition to DataComPy and would greatly enhance its usability for large datasets.

Best regards,
Suleyman Kaya.

**Comment by fdosani** [comment]
Hi @SuleymanKaya Have you looked into the Fugue or Spark implementation and maybe using some distributed framework like Spark or Dask? There are 2 options:

- [Fugue](https://capitalone.github.io/datacompy/fugue_usage.html)
- [Native Spark application](https://capitalone.github.io/datacompy/spark_usage.html)

These were designed specifically for datasets which are too large to fit into memory.

**Comment by SuleymanKaya** [comment]
Hi @fdosani, thank you for your response.

I appreciate the suggestion to use distributed computing frameworks like Spark or Fugue. These are indeed powerful tools for handling large datasets. However, my use case involves working with DataComPy specifically, and I am interested in enhancing its functionality to better handle chunked data.

While distributed computing frameworks are a solution for large datasets, they might not always be the most practical or accessible solution for all users or all use cases. The feature I proposed would allow users to handle large datasets directly within DataComPy, without the need to set up and use a distributed computing framework.

I understand that this would be a significant addition to DataComPy. I believe this feature would make DataComPy more versatile and user-friendly, especially for those working with large datasets.

Thank you for considering this proposal.

**Comment by fdosani** [comment]
@ak-gupta @NikhilJArora Any thoughts/opinions on this?

**Comment by fdosani** [comment]
@SuleymanKaya I've been thinking about this request, and I'm a bit torn. Right now we provide the functionality you are looking for via Spark, and Fugue (which can provide dask, spark, compatibility etc). I don't want to add unnecessary complexity to the code base. 

One of the issues with chunking locally is going to be pre-sorting cause if the common join items are in different chunks you will hit issues with the report being in-accurate. If you're dataset doesn't fit into memory then you should either bump up your compute to have more memory to accommodate (EC2 for instance) or just use some distributed computing framework like Spark.

Unfortunately I don't think I'm open to consider this proposal at this point in time cause it would literally mean overhauling the entire package and it would break all the functionality which currently exists and introduce complexity which is solve already via Spark (for example). Sorry for that. I'm going to close out this issue for now. Feel free to put your thoughts if you would like to add additional comments.
