### ISSUE TITLE
Datacompare for Date field is not working

### ISSUE THREAD

**Issue by RRajavel** [capitalone/datacompy#230]
Hi DataCompy Team,

I am comparing two dataset. Having issue in datetime field even though value is same it is returning as mismatch.

XXX  issuedt (Dataset1)   issuedt (Dataset2)
0    29291  2008-03-01 00:00:00  2008-03-01 00:00:00
1    34404  2003-12-01 00:00:00  2003-12-01 00:00:00
2    44191  2011-02-01 00:00:00  2011-02-01 00:00:00
3    53351                 None                 None
4    16526                 None                 None
5   140892  2014-06-01 00:00:00  2014-06-01 00:00:00
6    62895                 None                 None
7    77809                 None                 None
8    91280                 None                 None
9   131270  2020-08-26 00:00:00  2020-08-26 00:00:00

**Comment by fdosani** [comment]
Please paste the code and exact error you are getting so we can reproduce things on our end.

**Comment by RRajavel** [comment]
Hi [fdosani],

Thanks for the response. Please find the sample code. 

compare = datacompy.Compare(

            df,

            df1,

           

            # You can also specify a list

            # of columns

            join_columns = joincolumnlist,

           

            # Optional, defaults to 0

            abs_tol = 0,

           

            # Optional, defaults to 0

            rel_tol = 0,

           

            # Optional, defaults to 'df1'

            df1_name = 'Dataset1',

           

            # Optional, defaults to 'df2'

            df2_name = 'Dataset2' ,

            ignore_case= True

            )'

Here df & df1 are pandas dataframe. Data populated to the dataframe using SQL query. 
I am not getting any error. In the report output seeing discrepancy in the date field even though the value are same.

**Comment by fdosani** [comment]
Sorry for the delay but I need some more details. Like the actual data being used would be helpful. Can you post a command on a minimal piece of code to create `df`, `df1`. Also what should `joincolumnlist` be?

**Comment by fdosani** [comment]
Feel free to reopen this issue if needed. Closing for now due to no response.
