### ISSUE TITLE
Add list of dissimilar columns to report

### ISSUE THREAD

**Issue by janinebp** [capitalone/datacompy#235]
to be displayed after the number of columns in df1 but not df2 and vice-verssa

**Comment by janinebp** [comment]
branch push rejected..

**Comment by fdosani** [comment]
Hi there,

It would be helpful to provide some more details with what you are after here. With some visual examples and some more detail so our team can consider your feature request. 

Thanks in advance.

**Comment by janinebp** [comment]
just noticed this has been proposed in https://github.com/capitalone/datacompy/issues/222

Happy to help

**Comment by fdosani** [comment]
@janinebp if you or anyone else wants to submit a PR I'd be open to that!

**Comment by fdosani** [comment]
Feel free to reopen this issue, but assuming this is stale now and not being worked on by @janinebp or @lva290

**Comment by janinebp** [comment]
I tried but was not able to push code 
```
git push --set-upstream origin feature/display_dissimilar_columns_in_report
remote: Permission to capitalone/datacompy.git denied to janinebp.
```

**Comment by fdosani** [comment]
You need to make a fork and then push.   
On Tue, Mar 5, 2024 at 4:33 AM, janinebp ***@***.***&gt; wrote:  I tried but was not able to push code
git push --set-upstream origin feature/display_dissimilar_columns_in_report
remote: Permission to capitalone/datacompy.git denied to janinebp.
