### ISSUE TITLE
Restrictive dependency versions - NumPy 1.24.4 blocked

### ISSUE THREAD

**Issue by jason-vitaler** [capitalone/datacompy#237]
My project wants to update to NumPy 1.24.4, however this is being blocked by datacompy dependency constraints in the pyproject.toml.

The dependency rules in datacompy for NumPy are currently `numpy<=1.24.3,>=1.22.0`.

From looking through NumPy release history it seems as though they restrict breaking changes to the second block in the version string (in Semantic Versioning this would be the "minor" position).

Would it be possible to update the restriction in datacompy so that it becomes `numpy<1.25,>=1.22.0`?

**Comment by fdosani** [comment]
Hey @jason-vitaler Let me take a look!
Going to run edgetest against it and see if there are any issues.

**Comment by fdosani** [comment]
Seems like the bump to Pandas 2 is causing some issues too. See the following edgetest run: https://github.com/capitalone/datacompy/actions/runs/6277350903/job/17048905414

Will get out a fix for updating everything. Looking to get up to the following upper pins:

```
=============  ===============  ===================  =================
Environment    Passing tests    Upgraded packages    Package version
=============  ===============  ===================  =================
core           False            fugue                0.8.6
core           False            numpy                1.26.0
core           False            ordered-set          4.1.0
core           False            pandas               2.1.1
=============  ===============  ===================  =================
```

**Comment by jason-vitaler** [comment]
That would be greatly appreciated.  Thank you!

**Comment by fdosani** [comment]
More precisely this is a duckdb issue affecting fugue: https://github.com/duckdb/duckdb/pull/8738
I'll bump up the numpy version for now to unblock @jason-vitaler

**Comment by fdosani** [comment]
@jason-vitaler FYI: https://pypi.org/project/datacompy/0.10.4/

**Comment by jason-vitaler** [comment]
Thanks @fdosani !!
