### ISSUE TITLE
confused about df_unq_rows

### ISSUE THREAD

**Issue by swloveydp** [capitalone/datacompy#243]
hi  i have two dataframe 
i am not clear why df1_unq_row as picture below
![image](https://github.com/capitalone/datacompy/assets/16555783/7dfd426f-7c3d-4456-b559-cf5d29dc924a)

**Comment by fdosani** [comment]
Can you provide some more details like the code you executed so I can help answer your question. I'm guessing your join key is `vc_code`? If so then you this might help explain the differences you are seeing: https://capitalone.github.io/datacompy/pandas_usage.html#duplicate-rows

If you can post your actual code and data schema that would help in at least recreating the issue and figuring out what you are seeing.
