### ISSUE TITLE
Add mypy to the project

### ISSUE THREAD

**Issue by aguiddir** [capitalone/datacompy#247]
💬 Are you considering adding mypy to the project ?

**Comment by fdosani** [comment]
@aguiddir I'm open to it, would you be interested in contributing?

**Comment by aguiddir** [comment]
> @aguiddir I'm open to it, would you be interested in contributing?

@fdosani Sure, with pleasure! I can try to submit a PR if you'd like :+1:

**Comment by fdosani** [comment]
> @fdosani Sure, with pleasure! I can try to submit a PR if you'd like 👍

Awesome, appreciate that!

**Comment by fdosani** [comment]
Closed by #249
