### ISSUE TITLE
Rebuild docs automagically with Travis

### ISSUE THREAD

**Issue by theianrobertson** [capitalone/datacompy#25]
Need to dig into this a bit more, but this would probably mean moving docs to the gh-pages branch, and rebuilding every time there's a commit to master.

**Comment by fdosani** [comment]
Doing the `gh-pages` on `locopy` if you want to steal anything.
https://capitalone.github.io/Data-Load-and-Copy-using-Python/developer.html#generating-documentation

**Comment by fdosani** [comment]
No longer using Travis. Closing
