### ISSUE TITLE
Issue in writing report 

### ISSUE THREAD

**Issue by rangav07** [capitalone/datacompy#256]
What could possibly throw this error while writing report?

```
compare = datacompy.Compare(
        source,
        target,
        join_columns=keys,
        on_index=False,
        ignore_spaces=True,
        df1_name='Source',
        df2_name='Target'
    )  
```

  ```
with open(output_file, 'w', encoding='utf-8') as report_file:
         report_file.write(compare.report(sample_count=reportLimit, column_count=reportLimit))
   File "\lib\site-packages\datacompy\core.py", line 627, in report
    column["column"], sample_count, for_display=True
  File "\lib\site-packages\datacompy\core.py", line 482, in sample_mismatch
    sample = self.intersect_rows[~col_match].sample(sample_count)
  File "lib\site-packages\pandas\core\generic.py", line 4995, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 946, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by fdosani** [comment]
I'd need a bit more information to debug like a minimal example to recreate the issue you are facing. But just googling the error gives a pretty good idea of what might be happening. See [here.](https://stackoverflow.com/questions/71031769/valueerror-cannot-take-a-larger-sample-than-population-when-replace-false-usi)

Most likely `sample_count` is greater than what is in `intersect_rows` based on this: 

```python
File "\lib\site-packages\datacompy\core.py", line 482, in sample_mismatch
  sample = self.intersect_rows[~col_match].sample(sample_count)
```

But like I mentioned having a minimal example to reproduce the error would help identify if this is a bug.

**Comment by fdosani** [comment]
@rangav07 any updates?

**Comment by rangav07** [comment]
Hi,



datacompy version - 0.8.4

The full traceback of the error

`

Traceback (most recent call last):
  File "hist_compare.py", line 533, in <module>
    compare_result, compare_obj, name_of_file = data_compare(source_data, target_data, unique_keys)
  File "hist_compare.py", line 236, in data_compare
    report_file.write(compare.report(sample_count=reportLimit, column_count=reportLimit))
  File "/usr/local/lib/python3.8/site-packages/datacompy/core.py", line 624, in report
    self.sample_mismatch(
  File "/usr/local/lib/python3.8/site-packages/datacompy/core.py", line 480, in sample_mismatch
    sample = self.intersect_rows[~col_match].sample(sample_count)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5773, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/sample.py", line 150, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
  File "mtrand.pyx", line 984, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

`
I could see the sample_count value is less than intersect_rows dataframe

![image](https://github.com/capitalone/datacompy/assets/70570697/0d669375-7736-4512-80ed-e341cacc83b0)

Another error on the same line,

`
Traceback (most recent call last):
  File "hist_compare.py", line 533, in <module>
    compare_result, compare_obj, name_of_file = data_compare(source_data, target_data, unique_keys)
  File "hist_compare.py", line 236, in data_compare
    report_file.write(compare.report(sample_count=reportLimit, column_count=reportLimit))
  File "/usr/local/lib/python3.8/site-packages/datacompy/core.py", line 624, in report
    self.sample_mismatch(
  File "/usr/local/lib/python3.8/site-packages/datacompy/core.py", line 480, in sample_mismatch
    sample = self.intersect_rows[~col_match].sample(sample_count)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5773, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/sample.py", line 150, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

`

**Comment by fdosani** [comment]
@rangav07 a minimal reproducible example would be help here.

**Comment by fdosani** [comment]
@rangav07 pinging again for a MRE. Thanks!

**Comment by rangav07** [comment]
Unfortunately, I can't share the sample data due to compliance issue, but this is what is happening. 

1.  Get source data (Oracle) and order the data by primary keys for comparison.
2.  Get target data (Oracle) and order the data by same set of primary keys for comparison.
3.  Pass the data to datacompy as pandas dataframe

```
compare = datacompy.Compare(
        source,
        target,
        join_columns=keys,
        ignore_spaces=True,
        on_index=False,
        df1_name='Source_Oracle',
        df2_name='Target_SnowFlake'
    )
```
the issue occurs when there are no primary keys for the table and comparison done using index.

```
compare = datacompy.Compare(
            source,
            target,
            ignore_spaces=True,
            on_index=True,
            df1_name='Source_Oracle',
            df2_name='Target_SnowFlake'
        )
```

**Comment by fdosani** [comment]
So this is what I did to try and recreate, but I'm not getting an error. We don't need your exact data but something close and small enough to reproduce the issue.

```python
from io import StringIO
import pandas as pd
import datacompy

data1 = """acct_id,dollar_amt,name,float_fld,date_fld
10000001234,123.45,George Maharis,14530.1555,2017-01-01
10000001235,0.45,Michael Bluth,1,2017-01-01
10000001236,1345,George Bluth,,2017-01-01
10000001237,123456,Bob Loblaw,345.12,2017-01-01
10000001238,1.05,Lucille Bluth,,2017-01-01
10000001238,1.05,Loose Seal Bluth,,2017-01-01
"""

data2 = """acct_id,dollar_amt,name,float_fld
10000001234,123.4,George Michael Bluth,14530.155
10000001235,0.45,Michael Bluth,
10000001236,1345,George Bluth,1
10000001237,123456,Robert Loblaw,345.12
10000001238,1.05,Loose Seal Bluth,111
"""

df1 = pd.read_csv(StringIO(data1))
df2 = pd.read_csv(StringIO(data2))

df1 = df1.set_index("acct_id")
df2 = df2.set_index("acct_id")

compare = datacompy.Compare(
            df1,
            df2,
            ignore_spaces=True,
            on_index=True,
            df1_name='Source_Oracle',
            df2_name='Target_SnowFlake'
        )
```

The above works just fine. Are you having the issue when using an `index` or `key` (`join_on`)?
Even using a join key works fine for me:

```
df1 = df1.reset_index()
df2 = df2.reset_index()
compare = datacompy.Compare(
        source,
        target,
        join_columns=["acct_id"],
        ignore_spaces=True,
        df1_name='Source_Oracle',
        df2_name='Target_SnowFlake'
    )

print(compare.report())
```

**Comment by fdosani** [comment]
@rangav07 Any updates? If all is good then we will close out this issue by EoD

**Comment by fdosani** [comment]
Feel free to reopen if needed.
