### ISSUE TITLE
SparkCompare [PARSE_SYNTAX_ERROR] if column name contains unicode symbols

### ISSUE THREAD

**Issue by kformanowicz-dotdata** [capitalone/datacompy#280]
Script to reproduce:
```
from pyspark.sql import SparkSession
import datacompy

spark = SparkSession.builder.getOrCreate()

df1 = spark.createDataFrame(
    [
        (1, "foo"),
        (2, "bar"),
    ],
    ["id", "例"]
)

df2 = spark.createDataFrame(
    [
        (1, "foo"),
        (2, "baz"),
    ],
    ["id", "例"]
)

comp = datacompy.SparkCompare(spark, df1, df2, join_columns=["例"])
comp.report()
```

It seems that unicode chars are not escaped correctly when building SQL query for compare.

**Comment by fdosani** [comment]
Thanks for reporting. Will take a look into this shortly

**Comment by fdosani** [comment]
@kformanowicz-dotdata I have a fix for our new pyspark implementation [here](https://github.com/capitalone/datacompy/pull/275/commits/5caf78226b9f0733fbda672c3797e6ff1c827a89). 

I'll work on getting a legacy fix also. Just an FYI the legacy spark will eventually be deprecated in favour to align on the above.
