### ISSUE TITLE
Please add Snowpark support

### ISSUE THREAD

**Issue by achrusciel** [capitalone/datacompy#290]
https://docs.snowflake.com/en/developer-guide/snowpark/python/index

Snowflake is a popular database management system (dbms). It is really fast and easy to handle. Snowpark is a dataframe api implementation which is close to spark, but not exactly the same. I ran a sample code with datacompy and the reports for "Column Summary" and "Schema Differences" work well out-of-the-box. The execution fails with the report "Row Summary". When looking at the query executed against Snowflake it is visible that the syntax is not compatible with Snowflake. Seems to be a different dialect/syntax required. I'v rewritten parts of the "faulty" query and I got results.

**Comment by fdosani** [comment]
@achrusciel thanks for the feature request. Happy to accept a PR if you have the time to contribute? I can also take a closer look at this in a bit here. Totally open to adding in the support if you and others would find this helpful.

**Comment by fdosani** [comment]
FYI, we have a PR for snowpark support #333 
Another option I was thinking about was looking into https://ibis-project.org/ (cc: @gforsyth 😄 )

**Comment by fdosani** [comment]
#333 has been merged. Next release should have support.
