### ISSUE TITLE
`Compare` method is modifying input dataframes

### ISSUE THREAD

**Issue by william-chu-github** [capitalone/datacompy#292]
I am finding that the `Compare` method is modifying the input dataframes, which is very nonintuitive. In this particular case, it's downcasing the column names. I see there is an option to `cast_column_names_lower` defaulting to `True`, but my expectation is that this would downcase *for comparison purposes only* and not modify the original datasets. Is this intentional behaviour?

Here is a session showing how to reproduce the issue.

```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import datacompy
>>> datacompy.__version__
'0.11.3'
>>> import pandas
>>> df1 = pandas.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df2 = pandas.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df1
   A  B
0  1  4
1  2  5
2  3  6
>>> df2
   A  B
0  1  4
1  2  5
2  3  6
>>> df1.columns
Index(['A', 'B'], dtype='object')
>>> dfc = datacompy.Compare(df1, df2, join_columns = "A", df1_name = "from1", df2_name = "from2")
>>> df1
   a  b
0  1  4
1  2  5
2  3  6
>>> df1.columns
Index(['a', 'b'], dtype='object')
>>> df1 = pandas.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df2 = pandas.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> dfc = datacompy.Compare(df1, df2, join_columns = "A", df1_name = "from1", df2_name = "from2", cast_column_names_lower = False)
>>> df1
   A  B
0  1  4
1  2  5
2  3  6
>>> df2
   A  B
0  1  4
1  2  5
2  3  6
>>> 
```

**Comment by fdosani** [comment]
Thanks for flagging this @william-chu-github . This is the expected beahviour. Are you able to just set `cast_column_names_lower = False` or is there some other underlying issues with using that?

**Comment by william-chu-github** [comment]
Yes, I can use `cast_column_names_lower` to prevent the behaviour. It's just very nonintuitive to me that a comparison procedure would, by default, permanently modify the input datasets, especially given that the procedure is inspired by PROC COMPARE of SAS, which wouldn't do that sort of thing.

Thank you for confirming this is expected. I will close and just ensure I use `cast_column_names_lower = False` going forward.
