### ISSUE TITLE
Comparison result is completely wrong

### ISSUE THREAD

**Issue by mdivk** [capitalone/datacompy#31]
I use this tool to compare two parquets and surprisingly found the comparison result is completely wrong:
The two parquet files both has 40 fields with exactly the same name, difference is one parquet is 27MB and the other is 250MB.
Here is the summary:

Column Summary
--------------

Number of columns in common: 7
Number of columns in first_parquet but not in second_parquet: 33
Number of columns in second_parquet but not in first_parquet: 25

I understand it would help your troubleshooting if you have the actual parquet files, but unfortunately I can't give the files, a screenshot of the schemas side-by-side is here:
https://snag.gy/rnpmBX.jpg

**Comment by theianrobertson** [comment]
Hmm, that seems strange.  Are you able to provide a code snippet of loading in the parquet files to dataframes so I could generate my own sample data and try it out?

**Comment by mdivk** [comment]
I have changed my approach and used spark to read and compare the schema and it works for me, thank you.
