### ISSUE TITLE
SparkSQLCompare only works when grpcio and protobuf are installed manually outside of datacompy

### ISSUE THREAD

**Issue by shreya-goddu** [capitalone/datacompy#319]
v0.13.1 requires installing grpcio and protobuf and does not come with the datacompy install

`ImportError: grpcio >= 1.48.1 must be installed; however, it was not found.`

`ModuleNotFoundError: No module named 'google.protobuf'`

**Comment by fdosani** [comment]
@shreya-goddu did you pip install with the `spark` option?

`spark = ["pyspark[connect]>=3.1.1; python_version < \"3.11\"", "pyspark[connect]>=3.4; python_version >= \"3.11\""]`

**Comment by shreya-goddu** [comment]
if we want to use both pandas and spark do we need to install datacompy and datacompy[spark]

**Comment by fdosani** [comment]
No, Just: `pip install datacompy[spark]`

**Comment by fdosani** [comment]
Closing this issue, which should be resolved now.
