### ISSUE TITLE
SparkSQLCompare only checks for instance "pyspark.sql.DataFrame", but not for instance "pyspark.sql.connect.dataframe.DataFrame"

### ISSUE THREAD

**Issue by achrusciel** [capitalone/datacompy#320]
<img width="1092" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/3bed0f8c-3c60-40bd-9699-b4566557b0b2">
<img width="354" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/302973c6-7e3d-4bf4-8449-6bd199b0ad98">
<img width="554" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/a7dbe0ca-356e-4747-a456-e6441431a557">
<img width="477" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/de0aa96a-6f9e-433a-91e8-62f8c1468b86">

I am using Databricks pyspark:
![image](https://github.com/capitalone/datacompy/assets/25480933/8c4790d9-d70e-43e4-84d8-8cb8c5621082)

When using "from datacompy.spark.legacy import LegacySparkCompare as SparkCompare" the comparison works well.

**Comment by fdosani** [comment]
@achrusciel which version of datacompy are you using?

**Comment by achrusciel** [comment]
This is my docker image:
<img width="480" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/afbb6e40-0b44-445d-bed8-e357c3528082">

**Comment by achrusciel** [comment]
Sure, this is the result:
<img width="406" alt="image" src="https://github.com/capitalone/datacompy/assets/25480933/6c240174-e15e-485c-9619-3518abaa5914">

**Comment by fdosani** [comment]
> Sure, this is the result: <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/25480933/347441737-6c240174-e15e-485c-9619-3518abaa5914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjE0NjIsIm5iZiI6MTcyMDYyMTE2MiwicGF0aCI6Ii8yNTQ4MDkzMy8zNDc0NDE3MzctNmMyNDAxNzQtZTE1ZS00ODVjLTk2MTktMzUxOGFiYWE1OTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDE0MTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZDQ0ODMyNWMwZGUzNTc5Y2M4MDc1NDA4Zjg4ZDYyZTY3ZDc5OTZkODFlNmY3ZTEzNWZhZjU2NTllZDlkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LCEYE-nZ6J57f7XSSJFm5NxPQV-KC1_XYHNlZGLB-g">

Ok that is what the issue is then. I mean that seems like a bug in Databricks to me. The pyspark version is not `13.3.3`

**Comment by achrusciel** [comment]
Thank you for your efforts and quick responses. Highly appreciated.
