### ISSUE TITLE
Fixes for numpy 2.0 support

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#323]
`edgetest` is failing on numpy 2+ as seen here: https://github.com/capitalone/datacompy/actions/runs/9811778718/job/27094423048

Need investigating and remediation.

**Comment by filbranden** [comment]
Hi 👋 

Any updates on support for numpy 2?

I noticed that latest release 0.14.0 from last week still pins numpy on version 1

A version with support for numpy 2 (preferrably including numpy 2.1) would be greatly appreciated, thanks!

Thanks!

**Comment by filbranden** [comment]
BTW please also bump pandas to allow 2.2.3 (or 2.2.x, possibly <2.3.0 but no reason not to allow patch versions) without a pip conflict, thanks!

**Comment by fdosani** [comment]
@filbranden thanks for the reminder. There are some weird conflicts between Spark, Pandas, and numpy at different versions. The matrix quickly grows out of control. The main culprit is: `SparkPandasCompare`. I'm mulling the idea of dropping it all together from the package in favour of the SparkSQL variant. Also numpy 2+ I believe has a Python 3.10 min version.

**Comment by fdosani** [comment]
@ak-gupta @jdawang @gladysteh99 would appreciate your thoughts and opinions here.

**Comment by filbranden** [comment]
Thanks!

numpy 2.0 has Requires-Python: >=3.9, numpy 2.1 dropped Python 3.9 so numpy 2.1 is Python 3.10+
