### ISSUE TITLE
Return inner-joined data with comparisons

### ISSUE THREAD

**Issue by ModeltownMayor** [capitalone/datacompy#33]
It would be useful to be able to analyze a dataset based on the comparison, for example: 

Compare dataset A, B: approximately 2% do not match on my relative tolerance threshold for variable X.  I would like to get a dataset that has the inner join of A, B and an indicator variable for (difference in X > tol) that I could use for anlaysis.

As it stands I have to cook this myself, and I wasn't able to get sample_mismatch() to return what I needed easily

**Comment by fdosani** [comment]
@ModeltownMayor Sorry about the lack of response here. I'm going through and going to try and tackle all the issues in the repo this coming week. Not sure if this is still an issue for you. If you have a example bit of code that would be great.

**Comment by fdosani** [comment]
Closing issue. Please feel free to reopen if you have more details. Thanks!
