### ISSUE TITLE
Add column names to column summary

### ISSUE THREAD

**Issue by MariusMerkleQC** [capitalone/datacompy#334]
Would it be possible to provide not only the _number_ of columns that are found in the original and not in the new but also the _names_ of these columns?

For example, in [this report](https://capitalone.github.io/datacompy/polars_usage.html#reports), it would be good to know that the column that is in original but not in new is named "date_fld".

![image](https://github.com/user-attachments/assets/ac845a3b-544b-4b1a-88da-9100a902975e)

**Comment by fdosani** [comment]
@MariusMerkleQC thanks for the feedback. I'll take a look into this shortly. Just busy with a few other things at the moment.

**Comment by fdosani** [comment]
@MariusMerkleQC made some tweaks and it looks like this now: 

```
Number of columns in common: 4
Number of columns in original but not in new: 1 ['date_fld']
Number of columns in new but not in original: 0 []
```

Does that work for you?

**Comment by MariusMerkleQC** [comment]
Yes, that works!
