### ISSUE TITLE
Entire data mismatch throws None 

### ISSUE THREAD

**Issue by fayasali** [capitalone/datacompy#34]
When two table have same schema and data were different. this will throws exception

**Comment by fdosani** [comment]
Thanks for raising the issue. Do you have a snippet of code with the output, just to help with reproducibility?

**Comment by fayasali** [comment]
The scenario is when the two tables have same schema and data set is entirely different.
Ex: 
Table A
col1 col2 col3
a      b      c
a      b      c
Table B
col1 col2 col3
d      a      f
g      f       g
 
The comparison "_print_row_matches_by_column" method thows error at SparkCompare 

The following is Exact Exception

Exception:  unsupported operand type(s) for +: 'int' and 'NoneType'

Stack Trace:
Traceback (most recent call last):
    if sum(self.columns_match_dict[key])== self.columns_match_dict[key][MatchType.MATCH.value]:
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by fayasali** [comment]
If the supplied join key mismatch its throws the execption.
