### ISSUE TITLE
Dependency on polars<=1.7.0 is too restrictive

### ISSUE THREAD

**Issue by filbranden** [capitalone/datacompy#348]
I recently upgraded polars to 1.11.0 on my venv to address some issues of previous versions, and I encountered `pip check` warnings about the datacompy requirements on it:

```
datacompy 0.14.1 has requirement polars<=1.7.0,>=0.20.4, but you have polars 1.11.0.
```

I understand this is perhaps coming from the idea that datacompy was not tested against polars above 1.7.0, but having such restrictive requirements can be hard to handle, since this is now blocking a polars upgrade (well, I'm getting it with an unclean `pip check` but that's not ideal) and there seems to be no real reason not to trust polars 1.11 to be that much different from 1.7 that it would not work.

Would it be possible to loosen that restriction a bit and require polars<2 instead? Assuming the API will stay the same throughout the 1.x series (which is kind of the point of major/minor versioning), you'd protect against a polars 2 upgrade that would likely or probably break things, but still allow normal minor upgrades to go through to address other issues that are unlikely to cause any breakage.

In any case, even if you'd like to keep it as restrictive as you've been keeping it, can you at least bump it up to 1.11.0 to address the issue at hand? Thanks!

**Comment by fdosani** [comment]
@jdawang @gladysteh99 would you guys mind looking into this. Sorry just OOO right now

**Comment by gladysteh99** [comment]
@filbranden the upper pin is updated in the develop branch, feel free to use that version before a new release!
