### ISSUE TITLE
Get docs hosted on capitalone.github.io

### ISSUE THREAD

**Issue by theianrobertson** [capitalone/datacompy#4]
Hey @SanthiSridharan are you able to give me a hand with this?  I've got the built docs in the `/docs` subfolder, but I think I need someone with full repo rights to tell GH where to serve pages from, and maybe some help getting the capitalone.github.io connection set up?

**Comment by SanthiSridharan** [comment]
ian , I have updated the repo description. Also updated your access privilege to this repo. You and faisal are admins to this repo. You have the capability to update the tags and docs.

**Comment by theianrobertson** [comment]
Hosted now https://capitalone.github.io/datacompy/ (after adding back `.nojekyll` which I always forget)
