### ISSUE TITLE
Drop Matching Rows and Columns in Mismatch Output for Readability. 

### ISSUE THREAD

**Issue by alegarpa** [capitalone/datacompy#42]
Currently the csv that's being written out has all the columns written out on a failed comparison making it harder to read with a larger data-set.
This is more of a feature request but the ability to only have columns that didn't match written to the mismatch csv would really help and speed up the QA process on our end.

**Comment by fdosani** [comment]
Thanks for opening this issue @alegarpa 
@theianrobertson thoughts on this feature request? 
It seems reasonable to me FWIW.

**Comment by fdosani** [comment]
Adding to roadmap and backlog.

**Comment by azadekhalaj** [comment]
@fdosani Hi Faisal. I am wondering if this issue is still existing and if yes, I can work on this issue or not. Thanks.

**Comment by fdosani** [comment]
> @fdosani Hi Faisal. I am wondering if this issue is still existing and if yes, I can work on this issue or not. Thanks.

Hey there, I don’t think we have anyone working on this. Happy to take the extra support on this if you want to take a crack at it! Thanks 😊

**Comment by azadekhalaj** [comment]
@fdosani Awesome! Thank you :)

**Comment by fdosani** [comment]
Fixed in #166

**Comment by alegarpa** [comment]
I never thanked ya'll for this publicly but @azadekhalaj and @fdosani thank you so much for updating the library! Happy new year!

**Comment by fdosani** [comment]
@alegarpa Happy new year too!

**Comment by azadekhalaj** [comment]
@alegarpa Your welcome! Happy new year :)
