### ISSUE TITLE
idea/question: Writing compare/output results in a structured format(sqlite, csv, json)

### ISSUE THREAD

**Issue by aayush-jain18** [capitalone/datacompy#43]
Having a structured format output can help in below cases
- There is a large number of differences between the two dataframes
- There is a need to filter, perform operations, generate dashboards on output/compare report 

||row_num|key[symbol:quotedate]|close (Original)|close (New)|numdiff|text (Original)|text (New)|textdiff |
|---|---|---|---|---|---|---|---|---|
0|4|[AAN:01-05-2016]|20.0|23.12|3.12||| | 
1|4|[AAN:01-05-2016]|1030099.0|1030097.0|-2||| |
2|7|[AAP:01-05-2016]||||b|a|True| |

**Comment by ZlatGod** [comment]
How did you manage to get this Output? 
I would like to have something like this as well.

**Comment by aayush-jain18** [comment]
Initially, I created the above reports manually. I started some work here (https://github.com/aayush-jain18/AllSpark) for some of the features that I needed like cli and structured compare report

**Comment by ZlatGod** [comment]
Got it. I need my output to look something like this as well. Will see if I can use your tool. 
Meanwhile, can you check my Issue as well? 
I just posted an issue a while ago. Not able to see more than 10 rows in the output.

**Comment by fdosani** [comment]
Thanks for the suggestion @aayush-jain18.
Are you thinking structured in the sense of a data frame of the output being returned?

**Comment by fdosani** [comment]
@aayush-jain18 I'm OK with this as a new feature. I think it could be helpful. @theianrobertson any thoughts or comments. I can add this to the backlog if there are no objections.
