### ISSUE TITLE
No. of rows shown in comparison are limited to 10. 

### ISSUE THREAD

**Issue by ZlatGod** [capitalone/datacompy#45]
'Sample Rows with Unequal Values' shows just 10 rows which are different. 
I want to see what changed in all the rows in the 2 dataframes, not just 10 rows. 

Is there a way I can see all the unequal rows? 

Please advise.

**Comment by fdosani** [comment]
Hey there, Thanks for the question.
So I think you could do this in a couple of ways:

This might not be idea but one option if you want to see a specific column and you know the number of records you'd like to sample

```python
compare.sample_mismatch(column="name", sample_count=1000)
```

Another option is to use:

```python
compare.intersect_rows
```
`intersect_rows` gives you a dataframe which you can then check the `*_match` fields. 

3rdly the following will also return more rows if you prefer the reporting format:

```
print(compare.report(sample_count=1000))
```

**Comment by ZlatGod** [comment]
Thanks a lot. I was able to configure my way to see all rows. 
I was wondering if there is an effective way to format parts of the compare.report output in a data frame?
I am thinking of converting the output to a CSV and then loading it as a dataframe. 
Please let me know if you have a better way of doing it.

**Comment by fdosani** [comment]
@ZlatGod when you say format, what do you mean exactly? Like visual formatting? Or something else. Sorry, just want to make sure I'm understanding correctly

**Comment by ZlatGod** [comment]
When you see the compare.report output there are a lot of sections in that output. 
Some of them are under the following headings: 
1. Columns with Unequal Values or Types
2. Sample Rows with Unequal Values

So out of all the sections in the output, I just want to capture the output data which is under the above-mentioned headings. Once I capture them, I want to convert it into a dataframe.
 
Refer the screen capture..might help you figure out. Thanks. 
![Capture](https://user-images.githubusercontent.com/45374720/65349818-f0f42980-dba9-11e9-959a-7cd74a18599e.PNG)

**Comment by fdosani** [comment]
I think `compare.column_stats` would give you the above in a `dict` format.
Does that help?

**Comment by fdosani** [comment]
Closing the issue. Feel free to reopen it if you need.

**Comment by ramakanth1997** [comment]
Can I get the full script and How the comparision for large data set with Maximum columns
