### ISSUE TITLE
Are there any methods or any way to get different sections of the report individually? 

### ISSUE THREAD

**Issue by ZlatGod** [capitalone/datacompy#46]
For eg. 
When I run the report on my dataframes, I want only the output under the 'Columns with Unequal Values or Types' columns. 

I also want the output of 'Sample Rows with Unequal Values'. 

These are the only part of the compare.report I need. Is there any way to capture only this part of the report?

**Comment by fdosani** [comment]
@ZlatGod I think this is similar to https://github.com/capitalone/datacompy/issues/45 so I'll close this one and continue the conversation there.
