### ISSUE TITLE
Dropping support for Python 2?

### ISSUE THREAD

**Issue by fdosani** [capitalone/datacompy#48]
Wondering if we should have some conversation about dropping Python 2 support as it is coming soon to EOL. Right now we are support both, but it might help simplify things if we only go with 3.6+ in the next major release?

@theianrobertson @jborchma @gforsyth @slott56 Would appreciate any feedback on this.

**Comment by jborchma** [comment]
Let's drop it!

**Comment by fdosani** [comment]
I agree 👍

**Comment by gforsyth** [comment]
Strong agree. Drop it

**Comment by hugovk** [comment]
Please see PR #51.
