### ISSUE TITLE
Use type hinting & support Python 3.5+

### ISSUE THREAD

**Issue by dan-coates** [capitalone/datacompy#55]
Since we target Python 3.5+ in our CI testing, we can make this explicit and commit to only supporting that version and higher. This will enable us to use type hinting in our code, which would have a few benefits:

* IDE support for types while developing datacompy
* IDE support for types for users using datacompy
* Ability to do static type checking in our CI pipeline
* Automatic type inference during documentation generation

This should probably best be done in concert with something like #13 as long as we're messing with the code, but since this will involve committing to supporting certain versions of Python, it should be a conscious choice. Python 3.4 [reached EOL](https://devguide.python.org/devcycle/#end-of-life-branches) in March 2019 so I don't see a problem with explicitly targeting 3.5+.

**Comment by fdosani** [comment]
@dan-coates I might look into implementing this for the next release. I think we are away from Python 2 support so the minimum moving forward will be 3.5+. did you want to take a crack? Or if you had other thoughts around this?

**Comment by jborchma** [comment]
I would actually propose to drop 3.5 support as well. A lot of major packages have dropped support for that version and the official EOL is not far off.

**Comment by fdosani** [comment]
Personally I think it makes sense to wait and do it once it is Officially
dead dead. Also I don’t think there is a huge cost at the moment to support
it.

**Comment by jborchma** [comment]
True, EOL for 3.5 is in September.

**Comment by fdosani** [comment]
Closing this as 3.5 is EOL and no longer part of the support plan.
