### ISSUE TITLE
Understanding Intersect_rows when df1 and df2 have one-to-many relationships

### ISSUE THREAD

**Issue by mangoLily** [capitalone/datacompy#56]
If I am trying to compare the intersect rows for the following two dataframes:
```
df1 = pd.DataFrame({'key': ['foo', 'bar', 'baz', 'foo'],
                   'value': [1, 2, 3, 5]              
                   })
df2 = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                    'value': [5, 6, 7]})

compare = datacompy.Compare(
            df1,
            df2,
            join_columns=['key'],  #You can also specify a list of columns
            abs_tol=0,
            rel_tol=0,
            df1_name='df1',
            df2_name='df2')
```
compare.intersect_rows only return the following rows:

key | value_df1 | value_df2 | _merge | value_match
-- | -- | -- | -- | --
foo | 1 | 5 | both | False
bar | 2 | 6 | both | False
baz | 3 | 7 | both | False

While I am expecting an additional row:

key | value_df1 | value_df2 | _merge | value_match
-- | -- | -- | -- | --
foo | 5 | 5 | both | True

In fact, when you use pandas merge on df1 and df2, you do see the last row in df1:

```
df1.merge(df2, how="outer", suffixes=("_df1", "_df2"), indicator=True, on='key')
```

key | value_df1 | value_df2 | _merge
-- | -- | -- | --
foo | 1 | 5 | both
foo | 5 | 5 | both
bar | 2 | 6 | both
baz | 3 | 7 | both

Why is the last row from df1 missing from intersect_row dataframe?

**Comment by mangoLily** [comment]
https://github.com/capitalone/datacompy/blob/master/datacompy/core.py#L209-L226

It seems when join columns are not unique in one of the data frames, datacompy will add an additional order column in both data frames so combo of join columns are unique. This will in effect remove the additional rows for the same duplicated join columns. 

**df1**

key | value | order
-- | -- | --
foo | 1 | 1
bar | 2 | 1
baz | 3 | 1
foo | 5 | 2


**df2**
  
| key | value | order
-- | -- | --
foo | 5 | 1
bar | 6 | 1
baz | 7 | 1

Could we review the original intent for data frames that does not have unique join columns? 
e.g. if we want to compare all account level information in the statement data set against the account level data set, how do we make sure all the account level info are correct in all statements?

**Comment by fdosani** [comment]
thanks @mangoLily. @theianrobertson any thoughts on the intent here?

**Comment by fdosani** [comment]
Tagging @jborchma for opinions also

**Comment by jborchma** [comment]
So an easy thing could be to have a toggle for deduping. However, this does have the potential to blow up the dataframe when there are more multiples.

**Comment by fdosani** [comment]
@mangoLily I'm going to close this issue as it has become stale, but feel free to reopen if it you'd like to revisit it. Working through and going to prio the backlog.
