### ISSUE TITLE
Idea: Output join_cols in sample rows output for the report

### ISSUE THREAD

**Issue by behanjc** [capitalone/datacompy#57]
For the individual column comparisons, the join_cols are always outputted followed by the values in df1, df2.

However for the Sample Rows Only in df1/df2, the first 10 columns are outputted.
Suggestion would be to force the output to show the join columns in this as well, as sometimes (for whatever reason) the join columns are not in the first 10. 

Having it present would make downstream investigations of mismatches easier, instead of having to use the pandas df index to locate the join columns (assuming your join columns are also typically the lookup columns for investigations).

**Comment by fdosani** [comment]
@behanjc I think this makes sense. If you have a simple snippet could you paste it would just ground the intent here. But basically maybe as a rule always have the join cols to start in the output and then throw the "first" 10 (not including the joins)

**Comment by fdosani** [comment]
@behanjc Just wanted to follow up on this. If this isn't relevant I'll close this issue. Feel free to reopen it up.
