### ISSUE TITLE
Doesnt take into account join columns when doing strip() of white spaces

### ISSUE THREAD

**Issue by PABNY** [capitalone/datacompy#59]
Join columns can have whitespaces as well,so ideally below section should be enhanced to check for ignore_spaces and strip() if it is true for string columns
This is causing complete mismatch of 2 dataframes here in case 1 of join column has space:

if on_index and join_columns is not None:
            raise Exception("Only provide on_index or join_columns")
        elif on_index:
            self.on_index = True
            self.join_columns = []
        elif isinstance(join_columns, str):
            self.join_columns = [join_columns.lower()]
            self.on_index = False
        else:
            self.join_columns = [col.lower() for col in join_columns]
            self.on_index = False

**Comment by fdosani** [comment]
Hey @PABNY would you be able to provide an example of your column names you are using? Typically when we create data frames the best practice would to use `_` in place of spaces. I'd like to look into this a bit more and have a discussion about this. thanks for raising the issue!

**Comment by PABNY** [comment]
Hi Faisal

Issue is in data itself having whitespaces in join columns not in column names.
Like 
JOIN_COL_1='B' in DF1
JOIN_COL_1 ='B ' in DF2
so below section should be enhanced or a new section should be there to take care of doing strip for join columns as well?
Below I guess takes care of stripping of only non join columns in 2 data-frames:
 try:
                if ignore_spaces:
                    if col_1.dtype.kind == "O":
                        col_1 = col_1.str.strip()
                    if col_2.dtype.kind == "O":
                        col_2 = col_2.str.strip()

**Comment by fdosani** [comment]
Ahh I see. Sorry I misunderstood the original comment there. OK, let me take a look in a bit. Just a bit busy ATM, so will get back to you shortly.

**Comment by fdosani** [comment]
@jborchma Thoughts on stripping the column names before processing? I'm ok with it but wanted to get your thoughts. Any downsides from your side?

**Comment by fdosani** [comment]
Example:

```
df1 = pd.DataFrame({"some_col": [i for i in range(10)], "id": [str(i) for i in range(10)]})
df2 = pd.DataFrame({"some_col": [i for i in range(10)], "id": [str(i)+ " " for i in range(10)]})

pdcompare = datacompy.Compare(df1, df2, join_columns="id")
print(pdcompare.report())
```

Which yields:

```
DataComPy Comparison
--------------------

DataFrame Summary
-----------------

  DataFrame  Columns  Rows
0       df1        2    10
1       df2        2    10

Column Summary
--------------

Number of columns in common: 2
Number of columns in df1 but not in df2: 0
Number of columns in df2 but not in df1: 0

Row Summary
-----------

Matched on: id
Any duplicates on match values: No
Absolute Tolerance: 0
Relative Tolerance: 0
Number of rows in common: 0
Number of rows in df1 but not in df2: 10
Number of rows in df2 but not in df1: 10

Number of rows with some compared columns unequal: 0
Number of rows with all compared columns equal: 0

Column Comparison
-----------------

Number of columns compared with some values unequal: 0
Number of columns compared with all values equal: 2
Total number of values which compare unequal: 0

Sample Rows Only in df1 (First 10 Columns)
------------------------------------------

   some_col id
5       5.0  5
6       6.0  6
3       3.0  3
4       4.0  4
1       1.0  1
2       2.0  2
9       9.0  9
0       0.0  0
7       7.0  7
8       8.0  8

Sample Rows Only in df2 (First 10 Columns)
------------------------------------------

    some_col  id
19       9.0  9 
10       0.0  0 
14       4.0  4 
13       3.0  3 
12       2.0  2 
11       1.0  1 
18       8.0  8 
17       7.0  7 
15       5.0  5 
16       6.0  6
```

**Comment by jborchma** [comment]
Don't really have any issues with that. Sounds like a nice feature to have

**Comment by PABNY** [comment]
My query,bug was mainly on key column values not name
Key column values are not getting stripped of whitespace
Strip of whitespace happens only for non key columns
