### ISSUE TITLE
Make lowercasing of column names optional

### ISSUE THREAD

**Issue by gandhis1** [capitalone/datacompy#74]
If you are using camel case naming conventions and have several multi-word column names, then automatic lowercasing of names will make the final result less readable.

There is only a need to lowercase when you have case-insensitive duplicates. If you do not, there is no need to disambiguate. So why not add an option to turn this off? If there are duplicates, then simply throw - it already does this, anyhow.

**Comment by fdosani** [comment]
Hi @gandhis1 Could you please provide a minimal working example of the issue at hand. Personally I think it would be helpful to ensure we are on the same page. Currently we have `cast_column_names_lower` which can set if you want to column names to be lower cased or not. Does this not help your issue? Or maybe I'm misunderstanding.

Thanks!

**Comment by gandhis1** [comment]
Ah I see this was added very recently.  In fact, the version on PyPi (0.70) doesn't even contain this feature yet, which is why I hadn't noticed it. This can be closed, although I hope you guys will be able to release the new version to PyPi soon?

**Comment by fdosani** [comment]
yeah we can do a minor release. I'll do one shortly.
