### ISSUE TITLE
Allow customization of comparison report

### ISSUE THREAD

**Issue by gandhis1** [capitalone/datacompy#75]
At present it does not seem the built-in comparison report accepts any parameters. For one, I would like to be able to set the row limit myself as far as how many differences are printed per field. By default this is 10 - I'd like to optionally change this.

Appreciate the use of smart defaults, but any hard-coded parameter - 10 or otherwise, I feel ought to be something that can be configured externally.

**Comment by fdosani** [comment]
If you can provide some examples of what you are looking for that would be great. This way the team can have a discussion about potential features from your request.

**Comment by gandhis1** [comment]
Closing, I found out this [already exists as well](https://capitalone.github.io/datacompy/api/datacompy.html#datacompy.core.Compare.report).
