### ISSUE TITLE
Project CLA

### ISSUE THREAD

**Issue by tmbjmu** [capitalone/datacompy#82]
@ryanshiroma Can you please sign the project CLA for datacompy project? If you plan to submit a PR in the near future, CLA-Assistant bot will prompt to to sign. If you aren't planning to submit any new PRs to the project, pls use this link to sign: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

We appreciate your contributions to the project and your understanding on the contribution requirement for CLA.

**Comment by tmbjmu** [comment]
@theianrobertson Can you please sign the project CLA for datacompy project? If you plan to submit a PR in the near future, CLA-Assistant bot will prompt to to sign. If you aren't planning to submit any new PRs to the project, pls use this link to sign: https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform 

We appreciate your contributions to the project and your understanding on the contribution requirement for CLA.

**Comment by tmbjmu** [comment]
@theianrobertson @ryanshiroma Just following up here. Pls let me know if you have questions.

**Comment by tmbjmu** [comment]
@fdosani Please let me know if there is a better medium by which to contact @theianrobertson and @ryanshiroma to obtain the aforementioned CLA signatures. Thanks!

**Comment by theianrobertson** [comment]
Signed

**Comment by ryanshiroma** [comment]
Hey sorry for the delay, signed.

**Comment by fdosani** [comment]
Closing, this has been completed.
