### ISSUE TITLE
Add "Sample Rows with Unequal Values" to SparkCompare

### ISSUE THREAD

**Issue by kavita-srinivasan** [capitalone/datacompy#83]
I'd love to see `SparkCompare` produce "Sample Rows with Unequal Values". This is a really useful section from the `pandas` version of `datacompy`.

**Comment by kavita-srinivasan** [comment]
@dan-coates, Faisal mentioned that you built out the Spark functionality. Is this a relatively easy feature to add?

**Comment by fdosani** [comment]
@kavita-srinivasan hoping to follow up on this and see if there was any action needed?
