### ISSUE TITLE
NameError: name 'F' is not defined - getting this issue in sparkCompare

### ISSUE THREAD

**Issue by souvikchattopadhyay** [capitalone/datacompy#84]
~\Anaconda3\lib\site-packages\datacompy\sparkcompare.py in <listcomp>(.0)
    521         def helper(c):
    522             # Create a predicate for each match type, comparing column values to the match type value
--> 523             predicates = [F.col(c) == k.value for k in MatchType]
    524             # Create a tuple(number of match types found for each match type in this column)
    525             return F.struct([F.lit(F.sum(pred.cast("integer"))) for pred in predicates]).alias(c)

NameError: name 'F' is not defined

**Comment by fdosani** [comment]
It would be helpful for debugging if you could provide some minimal code to get the following error. Just looking at your error message it isn't very clear what is going on. Maybe some code, what you tried to run, what version you are using etc..

**Comment by jborchma** [comment]
Closing this since there was never any follow up.
