### ISSUE TITLE
Tests are failing in Spark 3 with Python 3.7.x

### ISSUE THREAD

**Issue by jborchma** [capitalone/datacompy#93]
Apparently the test are failing when using Spark 3 with Python 3.7.x. See #91.

**Comment by fdosani** [comment]
will need to investigate this a bit more. Weird this is happening. Spark 3 should work with 3.7, it was more that spark 2.4.x had issues with 3.8

**Comment by jborchma** [comment]
Yeah, I am also curious about this. Seems like this might actually be an issue with the Spark code and not a version conflict.

**Comment by fdosani** [comment]
Seems like this might have to do with the order of the datasets being compared and unioned in the actual tests. Have a fix coming.
